import React, { createContext, useState, useEffect } from "react";

import CheckCircleIcon from "@material-ui/icons/CheckCircle";

export const TrendingDataContext = createContext();

const RandomNumbers = Math.floor(100000 + Math.random() * 900000);

export const TrendingDataProvider = (props) => {
  const [products, setProducts] = useState([
    {
      _id: "321",
      title: "Top 10 Visually Stunning Anime Fights 🔥 🔥",
      image:
        "https://i.ytimg.com/an_webp/n5GO0ZiE7rU/mqdefault_6s.webp?du=3000&sqp=CPTx64sG&rs=AOn4CLB83f-fP6DKkYoCBS7e5OBvKEnbKQ",
      channel: "AniStudio",
      channelImage:
        "https://yt3.ggpht.com/ytc/AKedOLQgkuNeyyBsDxR59dBEVm8aZRLyARzIrPQ1yMt2=s48-c-k-c0x00ffffff-no-rj",
      views: "234,932",
      timestamp: "12 months ago",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "#top10animefights #top10bestanimefights #bestanimefightscence",
      video: "https://www.youtube.com/watch?v=n5GO0ZiE7rU",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [""],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "322",
      title: "Top 10 Legendary Anime Fights [60 Fps] ᴴᴰ",
      image: "https://i.ytimg.com/an_webp/Yglxt331WoY/mqdefault_6s.webp?du=3000&sqp=CMbt64sG&rs=AOn4CLB4tXknNUvdx-hSTl0hs6Qe_hNmDQ",
      channel: "Indian AnimeBros",
      channelImage: "https://yt3.ggpht.com/ytc/AKedOLQtMIpJDgDRTkT52uF7gzMKU2njiYD0lwvisomo=s48-c-k-c0x00ffffff-no-rj",
      views: "5,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "#anime",
      video: "https://www.youtube.com/watch?v=Yglxt331WoY",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "323",
      title: "Top 10 Most Epic Anime Fights of 2020",
      image: "https://i.ytimg.com/an_webp/eJzAUHwcuAE/mqdefault_6s.webp?du=3000&sqp=CO_l64sG&rs=AOn4CLCEq5S17yR2rfuXOBCi7PSl5XYVog",
      channel: "VinniTube",
      channelImage: "https://yt3.ggpht.com/ytc/AKedOLQ6DO0kc2mt3NSe7NYptVe3ktzaAC4lJKAkAIjLfA=s48-c-k-c0x00ffffff-no-rj",
      views: "76,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "#ViniiTube #Anime #AnimeTops",
      video: "https://www.youtube.com/watch?v=eJzAUHwcuAE",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "324",
      title: "TOKYO REVENGERS = BLACK AIR FORCE ENERGY THE ANIME 2",
      image: "",
      channel: "Cj Dachamp",
      channelImage: "https://yt3.ggpht.com/uetNfw7zYp18g0Q61SjyWtJ5wSnk05tWLp22sC3E0xoFrkCRxsSxputt9MkuxGmrHZ0vre-LZNI=s48-c-k-c0x00ffffff-no-rj",
      views: "213,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "https://www.youtube.com/watch?v=e0ogNfICYek",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "325",
      title: "Top 20 Anime Fights Of The Century (So Far)",
      image: "",
      channel: "WatchMojo.com",
      channelImage: "https://yt3.ggpht.com/ytc/AKedOLQXzhKDjfkdf9IhL8YOZ0pvOkaoDIsBHWtRUtfMig=s48-c-k-c0x00ffffff-no-rj",
      views: "98,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "23",
      subscribersBy: "M",
      video: "https://www.youtube.com/watch?v=9IcSJEIMWX8",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "326",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "3,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "327",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "62,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "328",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "321,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "329",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "76,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3210",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "99,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3211",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "234,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3212",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "724,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3213",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "452,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3214",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "72,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3215",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "12,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3216",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "43,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3217",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "67,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3218",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "65,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3219",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "72,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3220",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "40,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3221",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "41,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3222",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "97,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3223",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "72,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3224",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "42,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3225",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "7,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3226",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "9,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3227",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "112,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3228",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "652,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3229",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "82,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3230",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "41,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3231",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "76,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3232",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "254,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3233",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "163,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3234",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "284,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
    {
      _id: "3235",
      title: "",
      image: "",
      channel: "",
      channelImage: "",
      views: "96,932",
      timestamp: "23",
      icon: <CheckCircleIcon />,
      filter: "minutes",
      tags: "",
      subscribers: "",
      subscribersBy: "",
      video: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,",
      maxViews: "K",
      images: [],
      commentQuantity: "3,945",
      comments: [
        {
          _id: "1",
          user: "Beasty",
          date: "1 year ago",
          comments: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          thumbsUp: "2,926",
          thumbsDown: "457",
          replies: "152",
          imgChannel:
            "https://yt3.ggpht.com/ytc/AKedOLSi-HsiLB_7ul79thQeWiRMLXl5K0hGftRUPuJF=s88-c-k-c0x00ffffff-no-rj",
        },
      ],
    },
  ]);

  const [cart, setCart] = useState([]);

  const addCart = (id) => {
    const check = cart.every((item) => {
      return item._id !== id;
    });
    if (check) {
      const data = products.filter((product) => {
        return product._id === id;
      });
      setCart([...cart, ...data]);
    } else {
      alert("The product has been added to cart.");
    }
  };

  useEffect(() => {
    const dataCart = JSON.parse(localStorage.getItem("dataCart"));
    if (dataCart) setCart(dataCart);
  }, []);

  useEffect(() => {
    localStorage.setItem("dataCart", JSON.stringify(cart));
  }, [cart]);

  const value = {
    products: [products, setProducts],
    cart: [cart, setCart],
    addCart: addCart,
  };

  return (
    <TrendingDataContext.Provider value={value}>
      {props.children}
    </TrendingDataContext.Provider>
  );
};
